# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Mod Properties
mod_id = alwaysshield
mod_name = Always Shield
mod_version = 1.2.1
mod_description = Removes the obnoxious block delay of the shield, so it works the moment you press Right-Click. No more delay and confusion!
mod_license = MIT
mod_authors = JustMili

maven_group = net.justmili.alwaysshield
archives_base_name = AlwaysShield

minecraft_version_constraint_forge = [26.1,)
minecraft_version_constraint_fabric = >=26.1-
supported_versions = *

# Publishing
publish.modrinth = [MODRINTH_MOD_ID]
publish.curseforge = [CURSEFORGE_MOD_ID]
